GET http://localhost:3000/actor/all

###
GET http://localhost:3000/actor/names

###
GET http://localhost:3000/actor/movies

###
POST http://localhost:3000/actor/add
Content-Type: application/json

{
    "name": "Zaid",
  "birthname": "Zaid Sandler",
  "birthdate": "2015-09-09",
  "birthplace": "Tetouan"
}

###
PUT http://localhost:3000/actor/update/Zaid
Content-Type: application/json

{
    "name": "Zaid",
  "birthname": "Zaid ghhgh",
  "birthdate": "2015-01-01",
  "birthplace": "Martil"
}

###
DELETE http://localhost:3000/actor/delete/Zaid
